sudo docker run -it -v /home/ubuntu/text-emotion-analyzer:/workspace \
-e IBM_WATSON_TONE_ANALYZER_PASSWORD=$IBM_WATSON_TONE_ANALYZER_PASSWORD \
-e IBM_WATSON_TONE_ANALYZER_URL=$IBM_WATSON_TONE_ANALYZER_URL \
-e IBM_WATSON_TONE_ANALYZER_USERNAME=$IBM_WATSON_TONE_ANALYZER_USERNAME \
-e MS_COGNITIVE_TEXT_ANALYZER=$MS_COGNITIVE_TEXT_ANALYZER \
text-analizer /bin/bash
